### ISSUE TITLE
getting "Cannot find module 'toastr'" with ember-toastr 1.6.0 and 1.6.1

### ISSUE THREAD

**Issue by etherelly** [knownasilya/ember-toastr#18]
It works fine on 1.5.0 for us but when running ember after upgrading to 1.6.0 or 1.6.1:

Cannot find module 'toastr'
Error: Cannot find module 'toastr'
   at Function.Module._resolveFileName (module.js:440:15)
...

**Comment by lennartp92** [comment]
I'm having the same issue. Forcing back to version 1.5.0 solved the issue but with version 1.6.1 the ember app is not starting.

**Comment by zomarg** [comment]
It seems that the addon is not adding the package using addPackageToProject but if you install moment in your application before installing addon then it works fine (just a workaround for now till the problem is found)

**Comment by knownasilya** [comment]
@GramozKrasniqi did your PR not solve the issue?

**Comment by zomarg** [comment]
@knownasilya found it don't shout at me when you see the PR lol

**Comment by knownasilya** [comment]
Try v1.6.2

**Comment by pjcarly** [comment]
I'm still getting this error. 
After clean installing via ember install ember-toastr

Ember-toastr version: 1.6.2
Ember version: 2.13
Ember cli version: 2.13.2
